### ISSUE TITLE
Problem targetting "wss"

### ISSUE THREAD

**Issue by odyright** [mateusvicente100/bird-socket-client#12]
I got exception class "EIdOSSLCouldNotLoadSSLLibrary".  may be related to indyopenssl?

**Comment by mateusvicente100** [comment]
What moment you got this exception?

**Comment by odyright** [comment]
When i tried to connect to a wss:// link.
workaround: i added 2 files (libeay32.dll, ssleay32.dll) into <Project Folder>/Win32/Debug for 32-bit Windows. as suggested by [Securing_Indy_Network_Connections](https://docwiki.embarcadero.com/RADStudio/Sydney/en/Securing_Indy_Network_Connections)
