### ISSUE TITLE
Incompatível com versões anteriores

### ISSUE THREAD

**Issue by andeerc** [mateusvicente100/bird-socket-client#14]
Versão não está compatível com versões anteriores do Delphi: 
Delphi que estou usando é o 10.2
![image](https://user-images.githubusercontent.com/25756713/205361408-a9b21530-e7a0-4f7d-a925-29689a5181ec.png)

**Comment by mateusvicente100** [comment]
Só tenho o Delphi 11. Pode ajustar as incompatibilidades que eu aceito o
seu pull request.

Em sex., 2 de dez. de 2022 às 15:30, Anderson da Campo <
***@***.***> escreveu:

**Comment by mateusvicente100** [comment]
Ajustado.
