### ISSUE TITLE
Memory leak detected

### ISSUE THREAD

**Issue by DeddyH** [mateusvicente100/bird-socket-client#18]
The private field "FHeader" of TBirdSocketClient is created inside the constructor, but never freed. To fix this, simply add FHeader.Free inside the destructor (e.g. right before the "inherited"-line).

**Comment by mateusvicente100** [comment]
Hello... I will make the changes, thank you.

Em qua., 25 de out. de 2023 às 05:53, DeddyH ***@***.***>
escreveu:

**Comment by mateusvicente100** [comment]
@cayque10 made this for us. Released today.
