### ISSUE TITLE
Range check error in android application

### ISSUE THREAD

**Issue by MarceloSchemmer** [mateusvicente100/bird-socket-client#19]
Estou iniciando os testes e consegui fazer tudo certinho usando o fmx desktop, agora quando vou compilar para android (mais especificamente android 13) ao pedir conexão é retornado um erro chamado : range check error. não sei oque fazer.  estou compilando no delphi 11 Alexandria obrigado desde já amigos :)

**Comment by mateusvicente100** [comment]
Bom dia. Eu não tenho total certeza se o indy está compatível com o Android 13. Talvez valeria testar no Delphi 12. Você tem informações em que momento exatamente ocorre o erro?

**Comment by MarceloSchemmer** [comment]
Boa tarde amigo, então, efetuando mais alguns testes acho que estou próximo da solução vamos ver se vc concorda

o erro acontece mais especificamente na função : LBirdSocket.Send('Hello Server'); ou seja a conexão é criada sem nenhum problema, com a ajuda do chat GPT ele me retornou que esse erro que eu mencionei anteriormente seria por conta de acessar um índice do array que não existe.

continuando mais a fundo da função send mais especificamente FSocket.Write(EncodeFrame(AMessage)); na função EncodeFrame, retirei o IFDEF Android,IOS e consegui mandar o texto para o servidor. na primeira mensagem ele dá um exception de um outro erro porém nas demais tentativas seguidas consigo enviar normalmente sem nenhum problema.

a nova mensagem de erro é : RenderLayouts(): Text lines are not matching rendering lines.

como tenho muito pouco conhecimento nisso estou pesquisando oque pode ser kkk mas se vc tiver uma luz estou a disposição para poder ajudar.

**Comment by mateusvicente100** [comment]
Bom dia amigo. Infelizmente esse final de ano estou atolado com os
projetos, mas posso tentar olhar com calma quando a tempestade passar.
Contudo, se você achar a solução eu ficaria grato se pudesse enviar o pull
request com ela nos fontes do projeto.

Em qua., 27 de dez. de 2023 às 15:34, Schemmer Marcelo <
***@***.***> escreveu:

**Comment by cayque10** [comment]
Fala ai, pessoal. Fiz algumas correções relacionadas ao problema citado.: https://github.com/mateusvicente100/bird-socket-client/pull/21
