### ISSUE TITLE
Additional query parameters (then found in socket.handshake.query object on the server-side).

### ISSUE THREAD

**Issue by ghost** [mateusvicente100/bird-socket-client#23]
Olá Mateus, como vai?

Desculpe minha ignorância, mas como podemos acrescentar parâmetros adicionais na conexão?

Ex.: Socket IO:
https://socket.io/docs/v4/client-options/#query

Client

import { io } from "socket.io-client";

const socket = io({
  query: {
    x: 42
  }
});

Server

io.on("connection", (socket) => {
  console.log(socket.handshake.query); // prints { x: "42", EIO: "4", transport: "polling" }
});

**Comment by mateusvicente100** [comment]
Bom dia. Nunca utilizei. No caso, eu moldo a minha mensagem, eu passo um
string no formato do JSON, com os atributos que quero, exemplo:
Body := TJSONObject.Create.AddPair('x', 42).AddPair('y', 10).ToString

No lado do server, converto essa string para JSON e pego o que quero.

Em ter., 9 de jul. de 2024 às 07:39, altivogoncalves <
***@***.***> escreveu:

**Comment by ghost** [comment]
Entendo,
Mas no caso você envia a string JSON após a conexão ter sido estabelecida correto? 
No caso do Socket IO o parâmetro é avaliado no momento da conexão.

Estou lhe perguntando porque preciso estabelecer conexão com um servidor que utiliza esse "handshake".

Acredito que esse recurso ainda não tenha sido implementado no BirdSocket, certo?

Obrigado pelo seu retorno e sua disponibilidade.
Só precisava confirmar mesmo e deixar como sugestão essa implementação.

**Comment by cayque10** [comment]
Olá. De acordo com a documentação a implementação do Socket IO é diferente do Websocket, portanto não o componente não teria compatibilidade com um servidor Socket IO.

https://socket.io/docs/v4/

![image](https://github.com/user-attachments/assets/7f409c7b-8d94-416c-b4e2-a8fc4d740670)

**Comment by mateusvicente100** [comment]
De acordo com a documentação do @cayque10 o componente não é compatível com o soket.io.

**Comment by ghost** [comment]
Consegui fazer a integração utilizando javascript.

Obrigado pelo retorno.
Sds.
