### ISSUE TITLE
Chinese string garbled，how to solve ？

### ISSUE THREAD

**Issue by im-starrain** [mateusvicente100/bird-socket-client#5]
Hello, when using websocket client, the returned Chinese string is garbled, how can I solve it?

**Comment by mateusvicente100** [comment]
Hello. I believe we will need to change an property on request header to
accept there Chinese string. Can you send me an example to test here?

**Comment by mateusvicente100** [comment]
@im-starrain did you change some thing in your header request to test?

**Comment by mateusvicente100** [comment]
Resolved in issue #10
