### ISSUE TITLE
When subscribe a websocket stream, get error:1408F092:SSL routines:SSL3_GET_RECORD:data length too long

### ISSUE THREAD

**Issue by wqmeng** [mateusvicente100/bird-socket-client#7]
Hello, 

When I subscribe a web-socket stream server, I get some SSL related errors,  Do you have noticed this?  Or do you have see these errors of your apps?

I  have tried all the method
sslvSSLv2, sslvSSLv23, sslvSSLv3, sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2, 

No will work over 20 minutes. 

Here are the errors

05/05/2021 17:09:46 | Connect
05/05/2021 17:09:56 | HTTP/1.1 101 Switching Protocols

05/05/2021 17:09:56 | 
Date: Wed, 05 May 2021 09:09:57 GMT

05/05/2021 17:09:56 | 
Connection: upgrade

05/05/2021 17:09:56 | 
Upgrade: websocket

05/05/2021 17:09:56 | 
Sec-WebSocket-Accept: UtfBQbBJXYyf0a6J0drDN6YFgyQ=

05/05/2021 17:14:57 | HeartBeat
05/05/2021 17:19:57 | HeartBeat
**05/05/2021 17:21:37 | error:1408F092:SSL routines:SSL3_GET_RECORD:data length too long**
05/05/2021 17:21:37 | Disconnected
05/05/2021 17:21:37 | Connect
05/05/2021 17:21:46 | HTTP/1.1 101 Switching Protocols

05/05/2021 17:21:46 | 
Date: Wed, 05 May 2021 09:21:47 GMT

05/05/2021 17:21:46 | 
Connection: upgrade

05/05/2021 17:21:46 | 
Upgrade: websocket

05/05/2021 17:21:46 | 
Sec-WebSocket-Accept: z0FHSXXAyEyHRIh3bEfe/pfydxI=

05/05/2021 17:24:58 | HeartBeat
**05/05/2021 17:26:19 | error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac**

First chance exception at $764EA6E2. Exception class EIdOSSLUnderlyingCryptoError with message **'error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number'.**

Thank you.

**Comment by mateusvicente100** [comment]
Hello @wqmeng I have never see this error before. Have you tried to test with HTML websocket connect to confirm that it is not a problema in your server? If you go to bird-socket-server, there are an sample folder that contains a HTML sample. Try to use that to connect to your server.

**Comment by wqmeng** [comment]
Hello, 

The websocket stream server URL is 
wss://stream.binance.com:9443/ws/btcusdt@trade
could try by your sample, and need add a error listener. I get errors every a few minutes,  and could use a label show only one line of data instead of log in the listbox, because the data is live and huge. 

Thank you.

**Comment by wqmeng** [comment]
Hello,  Yes， I tested from html in firefox and runs hours without any problem. 
Thank you.

**Comment by mateusvicente100** [comment]
I have other user with the same issue. But it's very hard to find time and
see this. I will try take a test  soon with your server.

Em qui., 6 de mai. de 2021 às 11:28, wqmeng ***@***.***>
escreveu:

**Comment by DeddyH** [comment]
Maybe you have to use the latest versions of the OpenSSL-Libraries?

**Comment by mateusvicente100** [comment]
Hi Deddy. It is a issue. I need to find a solution for this, but if you
have an idea that can help me a will accept your pull request.

Em ter., 1 de fev. de 2022 às 04:42, DeddyH ***@***.***>
escreveu:

**Comment by DeddyH** [comment]
I possibly found a solution here: [https://github.com/IndySockets/Indy/issues/372](url)
"TIdSSLIOHandlerSocketOpenSSL.PassThrough := false" seems to do the trick when facing the issue.

**Comment by djunny** [comment]
hi~ i think i have a solution to fixed this bug.

https://github.com/mateusvicente100/bird-socket-client/pull/11

**Comment by ya-vanka** [comment]
I still have this issue (
With TIdSSLIOHandlerSocketOpenSSL.PassThrough := false

Any ideas what can be the reason of this error?

**Comment by mateusvicente100** [comment]
Are you trying upload some file via websocket?

Em qua., 23 de abr. de 2025 às 17:40, ya-vanka ***@***.***>
escreveu:
